package com.bsquare.datav.trucksidetool.re;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DTCIn implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String code;

   private java.lang.Integer occurrences;

   private java.lang.Integer order;

   public DTCIn()
   {
   }

   public java.lang.String getCode()
   {
      return this.code;
   }

   public void setCode(java.lang.String code)
   {
      this.code = code;
   }

   public java.lang.Integer getOccurrences()
   {
      return this.occurrences;
   }

   public void setOccurrences(java.lang.Integer occurrences)
   {
      this.occurrences = occurrences;
   }

   public java.lang.Integer getOrder() {
      return this.order;
   }

   public void setOrder(java.lang.Integer order) {
      this.order = order;
   }

   public DTCIn(java.lang.String code, java.lang.Integer occurrences, java.lang.Integer order)
   {
      this.code = code;
      this.occurrences = occurrences;
      this.order = order;
   }

}